/**
 * Cisco Router configuration generator (Router-on-a-stick)
 */

interface SubInterfaceInput {
  vlanNumber: number;
  vlanName: string;
  gateway: string;
  mask: string;
  network: string;
}

interface RouterConfigInput {
  hostname: string;
  projectName: string;
  branchName: string;
  subInterfaces: SubInterfaceInput[];
  wanInterface?: string;
  wanNextHop?: string;
}

export function generateRouterConfig(input: RouterConfigInput): string {
  const now = new Date().toISOString();

  const lines: string[] = [
    `! ============================================`,
    `! Router Configuration: ${input.hostname}`,
    `! Generated by NetCraft AI`,
    `! Project: ${input.projectName}`,
    `! Branch: ${input.branchName}`,
    `! Date: ${now}`,
    `! ============================================`,
    ``,
    `! --- Basic Security ---`,
    `hostname ${input.hostname}`,
    `enable secret [CHANGE_ME]`,
    `service password-encryption`,
    `no ip domain-lookup`,
    ``,
    `! --- Console & VTY ---`,
    `line console 0`,
    ` password [CHANGE_ME]`,
    ` logging synchronous`,
    ` exec-timeout 5 0`,
    ` login`,
    `line vty 0 4`,
    ` password [CHANGE_ME]`,
    ` exec-timeout 5 0`,
    ` transport input ssh`,
    ` login`,
    ``,
    `! --- Banner ---`,
    `banner motd #`,
    `*** AUTHORIZED ACCESS ONLY ***`,
    `*** NetCraft AI Generated Config ***`,
    `#`,
    ``,
    `! --- Router-on-a-stick sub-interfaces ---`,
    `interface GigabitEthernet0/0`,
    ` no shutdown`,
  ];

  for (const sub of input.subInterfaces) {
    lines.push(``);
    lines.push(`interface GigabitEthernet0/0.${sub.vlanNumber}`);
    lines.push(` description ${sub.vlanName} Gateway`);
    lines.push(` encapsulation dot1Q ${sub.vlanNumber}`);
    lines.push(` ip address ${sub.gateway} ${sub.mask}`);
  }

  lines.push(``);
  lines.push(`! --- DHCP Pools ---`);

  for (const sub of input.subInterfaces) {
    // Skip native and blackhole
    if (sub.vlanNumber === 99 || sub.vlanNumber === 999) continue;

    lines.push(`ip dhcp excluded-address ${sub.gateway} ${sub.gateway}`);
    lines.push(`ip dhcp pool POOL_${sub.vlanName}`);
    lines.push(` network ${sub.network} ${sub.mask}`);
    lines.push(` default-router ${sub.gateway}`);
    lines.push(` dns-server 8.8.8.8`);
    lines.push(``);
  }

  lines.push(`! --- SSH ---`);
  lines.push(`ip domain-name netcraft.local`);
  lines.push(`crypto key generate rsa modulus 2048`);
  lines.push(`ip ssh version 2`);
  lines.push(``);
  lines.push(`! --- Default Route ---`);
  lines.push(
    `ip route 0.0.0.0 0.0.0.0 ${input.wanNextHop ?? "[NEXT_HOP]"}`
  );
  lines.push(``);
  lines.push(`end`);

  return lines.join("\n");
}
