/**
 * Cisco Switch configuration generator
 */

interface SwitchConfigInput {
  hostname: string;
  projectName: string;
  branchName: string;
  vlans: { number: number; name: string }[];
  departmentName: string;
  accessVlan: number;
  trunkAllowedVlans: number[];
  managementVlan: number;
  managementIp?: string;
  managementMask?: string;
  gateway?: string;
  accessPortCount: number;
  trunkPort: string;
  uplink: string;
}

export function generateSwitchConfig(input: SwitchConfigInput): string {
  const now = new Date().toISOString();
  const allowedStr = input.trunkAllowedVlans.join(",");

  const usedPorts = input.accessPortCount;
  const totalPorts = 24;
  const unusedStart = usedPorts + 1;

  const lines: string[] = [
    `! ============================================`,
    `! Switch Configuration: ${input.hostname}`,
    `! Generated by NetCraft AI`,
    `! Project: ${input.projectName}`,
    `! Branch: ${input.branchName}`,
    `! Date: ${now}`,
    `! ============================================`,
    ``,
    `! --- Basic Security ---`,
    `hostname ${input.hostname}`,
    `enable secret [CHANGE_ME]`,
    `service password-encryption`,
    `no ip domain-lookup`,
    ``,
    `! --- Console & VTY ---`,
    `line console 0`,
    ` password [CHANGE_ME]`,
    ` logging synchronous`,
    ` exec-timeout 5 0`,
    ` login`,
    `line vty 0 4`,
    ` password [CHANGE_ME]`,
    ` exec-timeout 5 0`,
    ` transport input ssh`,
    ` login`,
    ``,
    `! --- Banner ---`,
    `banner motd #`,
    `*** AUTHORIZED ACCESS ONLY ***`,
    `*** NetCraft AI Generated Config ***`,
    `#`,
    ``,
    `! --- VLANs ---`,
  ];

  for (const v of input.vlans) {
    lines.push(`vlan ${v.number}`);
    lines.push(` name ${v.name}`);
  }

  lines.push(``);
  lines.push(`! --- Access Ports ---`);

  if (usedPorts > 0) {
    const range =
      usedPorts === 1
        ? `FastEthernet0/1`
        : `FastEthernet0/1-${usedPorts}`;
    lines.push(`interface range ${range}`);
    lines.push(` description ${input.departmentName}`);
    lines.push(` switchport mode access`);
    lines.push(` switchport access vlan ${input.accessVlan}`);
    lines.push(` spanning-tree portfast`);
    lines.push(` no shutdown`);
  }

  lines.push(``);
  lines.push(`! --- Trunk Ports ---`);
  lines.push(`interface ${input.trunkPort}`);
  lines.push(` description TRUNK to ${input.uplink}`);
  lines.push(` switchport mode trunk`);
  lines.push(` switchport trunk native vlan 99`);
  lines.push(` switchport trunk allowed vlan ${allowedStr}`);
  lines.push(` no shutdown`);

  if (unusedStart <= totalPorts) {
    lines.push(``);
    lines.push(`! --- Unused Ports ---`);
    const unusedRange =
      unusedStart === totalPorts
        ? `FastEthernet0/${unusedStart}`
        : `FastEthernet0/${unusedStart}-${totalPorts}`;
    lines.push(`interface range ${unusedRange}`);
    lines.push(` description UNUSED - SECURED`);
    lines.push(` switchport mode access`);
    lines.push(` switchport access vlan 999`);
    lines.push(` shutdown`);
  }

  lines.push(``);
  lines.push(`! --- Management ---`);
  lines.push(`interface vlan ${input.managementVlan}`);
  if (input.managementIp && input.managementMask) {
    lines.push(` ip address ${input.managementIp} ${input.managementMask}`);
  } else {
    lines.push(` ip address [FROM_SUBNET] [MASK]`);
  }
  lines.push(` no shutdown`);
  lines.push(`ip default-gateway ${input.gateway ?? "[GATEWAY]"}`);
  lines.push(``);
  lines.push(`! --- STP ---`);
  lines.push(`spanning-tree mode rapid-pvst`);
  lines.push(``);
  lines.push(`end`);

  return lines.join("\n");
}
