/**
 * Cisco Autonomous AP configuration generator
 */

interface ApConfigInput {
  hostname: string;
  projectName: string;
  branchName: string;
  ssidName: string;
  vlanNumber: number;
  managementIp?: string;
  managementMask?: string;
  gateway?: string;
}

export function generateApConfig(input: ApConfigInput): string {
  const now = new Date().toISOString();

  const lines: string[] = [
    `! ============================================`,
    `! AP Configuration: ${input.hostname}`,
    `! Generated by NetCraft AI`,
    `! Project: ${input.projectName}`,
    `! Branch: ${input.branchName}`,
    `! Date: ${now}`,
    `! ============================================`,
    ``,
    `! --- Basic Security ---`,
    `hostname ${input.hostname}`,
    `enable secret [CHANGE_ME]`,
    `service password-encryption`,
    ``,
    `! --- Console & VTY ---`,
    `line console 0`,
    ` password [CHANGE_ME]`,
    ` logging synchronous`,
    ` exec-timeout 5 0`,
    ` login`,
    `line vty 0 4`,
    ` password [CHANGE_ME]`,
    ` exec-timeout 5 0`,
    ` transport input ssh`,
    ` login`,
    ``,
    `! --- Banner ---`,
    `banner motd #`,
    `*** AUTHORIZED ACCESS ONLY ***`,
    `*** NetCraft AI Generated Config ***`,
    `#`,
    ``,
    `! --- Wireless SSID ---`,
    `dot11 ssid ${input.ssidName}`,
    ` vlan ${input.vlanNumber}`,
    ` authentication open`,
    ` authentication key-management wpa version 2`,
    ` wpa-psk ascii [CHANGE_ME_PSK]`,
    ` guest-mode`,
    ``,
    `! --- Radio 2.4 GHz ---`,
    `interface Dot11Radio0`,
    ` ssid ${input.ssidName}`,
    ` encryption vlan ${input.vlanNumber} mode ciphers aes-ccm`,
    ` no shutdown`,
    ``,
    `! --- Radio 5 GHz ---`,
    `interface Dot11Radio1`,
    ` ssid ${input.ssidName}`,
    ` encryption vlan ${input.vlanNumber} mode ciphers aes-ccm`,
    ` no shutdown`,
    ``,
    `! --- Management ---`,
    `interface BVI1`,
  ];

  if (input.managementIp && input.managementMask) {
    lines.push(` ip address ${input.managementIp} ${input.managementMask}`);
  } else {
    lines.push(` ip address [FROM_SUBNET] [MASK]`);
  }

  lines.push(` no shutdown`);
  lines.push(``);
  lines.push(`ip default-gateway ${input.gateway ?? "[GATEWAY]"}`);
  lines.push(``);
  lines.push(`end`);

  return lines.join("\n");
}
